#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the cpig command anywhere in a user's workspace.

if (echo $PYTHONPATH | grep -i -q "pdm/pep582" ) ; then
  echo PEP 582 enabled globally
else
  echo ""
  echo "PEP 582 has NOT been enabled globally"
  echo "To use this script you MUST follow the instructions in:"
  echo "  https://pdm.fming.dev/#enable-pep-582-globally"
  echo ""
  echo "Editable cpig command NOT created"
  echo ""
  exit -1
fi

cpigScript=$(pdm info | grep Packages | cut -d' ' -f5)/bin/cpig

cat << CPIG_SCRIPT > $HOME/.local/bin/cpig
#!/bin/sh

# This shell script was created by the ComputePods interfaceGenerator
#       './scripts/installEditableCpigCommand'
# script.

exec $cpigScript \$@
CPIG_SCRIPT

chmod a+x $HOME/.local/bin/cpig

echo ""
echo "Editable cpig command has been created"
echo ""
